name: CI

on:
  push:
    tags:        
      -*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1.1.0
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
